"""initial_schema

Revision ID: 09e1fa9b78eb
Revises: None
Create Date: 2026-07-01 10:56:04.172428+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09e1fa9b78eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_memory_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edges_relationship_type', 'knowledge_edges', ['relationship_type'], unique=False)
    op.create_index('ix_edges_source_target', 'knowledge_edges', ['source_node_id', 'target_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_source_node_id'), 'knowledge_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_target_node_id'), 'knowledge_edges', ['target_node_id'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('source_memory_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('pagerank_score', sa.Float(), nullable=False),
    sa.Column('degree_centrality', sa.Float(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nodes_entity_type', 'knowledge_nodes', ['entity_type'], unique=False)
    op.create_index('ix_nodes_name', 'knowledge_nodes', ['name'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_uri', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('decay_factor', sa.Float(), nullable=False),
    sa.Column('provenance_algorithm', sa.String(length=20), nullable=False),
    sa.Column('provenance_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_uri')
    )
    op.create_index('ix_memories_author', 'memories', ['author'], unique=False)
    op.create_index('ix_memories_created_at', 'memories', ['created_at'], unique=False)
    op.create_index('ix_memories_decay_factor', 'memories', ['decay_factor'], unique=False)
    op.create_index('ix_memories_source_type', 'memories', ['source_type'], unique=False)
    op.create_index('ix_memories_status', 'memories', ['status'], unique=False)
    op.create_index('ix_memories_updated_at', 'memories', ['updated_at'], unique=False)
    op.create_table('memory_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_memory_id_index', 'memory_chunks', ['memory_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_memory_chunks_memory_id'), 'memory_chunks', ['memory_id'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('classified_intent', sa.String(length=50), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_degraded', sa.Boolean(), nullable=False),
    sa.Column('total_time_ms', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_logs_user_created', 'query_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.drop_index('ix_query_logs_user_created', table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_memory_chunks_memory_id'), table_name='memory_chunks')
    op.drop_index('ix_chunks_memory_id_index', table_name='memory_chunks')
    op.drop_table('memory_chunks')
    op.drop_index('ix_memories_updated_at', table_name='memories')
    op.drop_index('ix_memories_status', table_name='memories')
    op.drop_index('ix_memories_source_type', table_name='memories')
    op.drop_index('ix_memories_decay_factor', table_name='memories')
    op.drop_index('ix_memories_created_at', table_name='memories')
    op.drop_index('ix_memories_author', table_name='memories')
    op.drop_table('memories')
    op.drop_index('ix_nodes_name', table_name='knowledge_nodes')
    op.drop_index('ix_nodes_entity_type', table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_edges_target_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_source_node_id'), table_name='knowledge_edges')
    op.drop_index('ix_edges_source_target', table_name='knowledge_edges')
    op.drop_index('ix_edges_relationship_type', table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    # ### end Alembic commands ###
